const ConstStrings = {
    welcome: "Welcome",
    welcomeToBando: "Welcome to Bando, just for",
    trueArtist: "true artists",
    applyNow: "APPLY NOW",
    signInWithYourEmail: "Sign in with your email",
    applyToJoinBando: "Apply to join Bando",
    inOrderToJoinBandoAsAnArtist: "In order to join Bando as an artist, simply fill",
    outTheFollowingApplication: "out the following application form.",
    firstName: "First Name",
    lastName: "Last Name",
    artistName: "Display Name",
    dateOfBirth: "Date of birth",
    optional: "optional",
    aboutYou: "About you",
    pleaseTellUsABitAboutYourself: "Please tell us a bit about yourself and why you want to join Bando.",
    whatWillYouUse: "What will you use",
    bandoFor: "bando for?",
    selectAllThatApply: "Select all that apply.",
    SocialMedia: "Social Media",
    addYourSocialMediaUrl: "Add your social media Url",
    spotify: "Spotify",
    website: "Website",
    facebook: "Facebook",
    instagram: "Instagram",
    soundCloud: "Soundcloud",
    finish: "FINISH",
    thanksForApplying: "Thanks for Applying",
    weWillBeInTouchViaEmail: "We’ll be in touch via email within 3 working",
    daysWithAnUpdateInYourApplication: "days with an update on your application. We’re",
    lookingForwardToWelcomingYou: "looking forward to welcoming you to the",
    platform: "platform!",
    ok: "OK",
    congratulations: "Congratulations",
    itLooksLikeYouHaveBeenAccepted: "It looks like you’ve been accepted to join",
    bandoWejustNeedYouToComplete: "Bando! We just need you to complete a few",
    shortStepsToCompleteYourAccount: "short steps to complete your account creation.",
    confirmPassword: "Confirm password",
    use8Characters: "Use 8 characters",
    useOneCaps: "Use one caps",
    useOneNumber: "Use one number",
    byClickingNextYouAgree: "By clicking next, you agree to our",
    terms: "Terms",
    termsEula: "Terms & EULA",
    and: "and",
    dataUsePolicy: "Data Use Policy",
    addYourPhone: "Add your phone",
    number: "number",
    specifyYourPhoneNumber: "Specify your phone number to confirm",
    yourAccount: "your account.",
    phoneNumber: "Phone Number",
    weWillSendToYouAMessage: "We will send to you a message to this",
    numberForYouToConfirm: "number for you to confirm.",
    addYourCode: "Add your code",
    addYourRecievedCodeBelow: "Add you received code below.",
    weSentTheCodeTo: "We sent the code to:",
    addCodeHere: "Add code here",
    resendCodeAgain: "Resend code again",
    addYourCover: "Add your cover",
    image: "image",
    addYourProfile: "Add your profile",
    photo: "photo",
    addPhoto: "Add Photo",
    youCanAddCoverPhoto: "You can add a cover photo later",
    youCanAddProfilePhoto: "You can add a profile photo later",
    insideYourProfilePage: "inside your profile page",
    skip: "SKIP",
    SubscriptionPricing: "Subscription Pricing",
    setYourMonthlyPrice: "Set your monthly price, and we’ll calculate",
    theThreePriceBandsForUsersToSubscribe: "the three price bands for users to subscribe",
    toYourContent: "to your content",
    oneMonth: "One Month",
    threeMonths: "Three Months",
    annual: "Annual",
    price: "Price",
    finalDetails: "Final details",
    addYourBioHereDescribeWhoYouare: "Add your Bio here. Describe who you are what",
    youHaveDoneTellUsAllAboutYou: "you have done. Tell us all about you.",
    bio: "Bio",
    ThanksForJoining: "Thanks for Joining",
    gToHomePage: "GO TO HOMEPAGE",
    newPost: "New Post",
    whatKindOfPostWouldYouLikeToCreate: "What kind of post would you like to create?",
    newImagePost: "New Image Post",
    newAudioPost: "New Audio Post",
    pleaseSelectGenre: "Please select genre",
    pleaseUploadYourImage: "Please upload your image",
    pleaseUploadYourAudio: "Please upload your audio",
    changephoto: "Change photo",
    changeVideo: "Change Video",
    changeAudio: "Change Audio",
    addAudio: "Add Audio",
    wantToAddACaptionForYourSubscriber: "Want to add a caption for your subscribers or",
    chooseAnItemOfMerchandiseToFeature: "choose an item of merchandise to feature?",
    descriptionOptional: "Description (optional)",
    title: "Title",
    post: "POST",
    uploadCover: 'Upload cover',
    useBandoLogo: 'Use bando Logo',
    newAudioPost: 'New Audio Post',
    newVideoPost: 'New Video Post',
    pleaseUploadYourAudio: 'Please upload your audio',
    pleaseUoloadYourVideo: 'Please upload your video',
    or: 'or',
    recoverYour: 'Recover your',
    password: 'password',
    enterYourEmailBelowDescription: `Enter your email below and we'll send you a`,
    linkToResetYourPassword: `link to reset your password.`,
    checkYourEmail: 'Check your email',
    weSentyouPassword: 'We sent you a password reset email.',
    pleaseMakeSuretocheckYourSpamFOlder: 'Please make sure to check your spam folder.',
    resendEmailAgain: 'Resend email again',
    done: 'DONE',
    reset: 'Reset',
    Password: 'Password',
    emailNotFound: 'Email not found.',
    useAnotherEmail: 'Use another email',
    videoMessage: 'Video must be greater then 10 second',
    audioMessage: 'Audio must be greater then 10 second',
    sorry: "Sorry",
    itLooksLikeYourApplicationToJoin: "It looks like your application to join Bando has",
    beenRejectedIfYouThink: "been rejected. If you think this is a mistake,",
    pleaseEmailInfo: "please email info@bando-app.com",
    merchandise: "Merchandise",
    merchandises: 'Merchandises',
    viewAll: "View All",
    audio: "Audio",
    audios: 'Audios',
    video: "Video",
    videos: 'Videos',
    photo: "Image",
    photos: 'Images',
    preview: 'PREVIEW',
    Stats: "Stats",
    Analytics: "Analytics",
    Statistics: "Statistics",
    Subscriptions: "Subscriptions",
    currentSubscribers: "Current Subscribers",
    subscriptionRevenue: "Subscriptions Revenue",
    merchandiseRevenue: "Merchandise Revenue",
    merchandising: "Merchandising",
    newSubscriber: "New Subscriber",
    merchandiseSell: "Merchandise Sale",
    termsAndCondition: "Terms and Conditions",
    termsAndEula: 'Terms and EULA',
    privacyPolicy: "Privacy Policy",
    paymentSettings: "Payment Settings",
    logout: "Logout",
    settings: "Settings",
    capitalNotifications: "NOTIFICATIONS",
    newMerch: "New Merch",
    newMerchDescription1: 'Please upload at least one image of the merch',
    newMerchDescription2: 'you intend to sell',
    uploadMore: 'Upload More',
    merchDetails: 'Merch details',
    merchDetailsDescription1: 'Add a title,description and specify the type',
    merchDetailsDescription2: 'of merch you want to sell.',
    merchName: 'Merch Name',
    merchType: 'Merch type',
    priceDetail: 'Price Details',
    priceDetailDescription1: 'Add information about the price and quanitity',
    priceDetailDescription2: 'available for your subscribers to purchase',
    captionAddingDescription1: 'Want to add a caption for your subscribers or',
    captionAddingDescription2: 'choose an item of merchandise to feature?',
    currencySymbol: '$',
    varitations: 'Variations',
    quanitity: 'Quantity',
    newMerch: "New Merch",
    description: 'Description',
    addItem: 'ADD ITEM',
    description: 'Description',
    addItem: 'ADD ITEM',
    addInformation: 'Add Information',
    addInformationDesc1: 'Give more information about the',
    addInformationDesc2: `merchandise you'd like to sell`,
    addVariation: 'Add at least one variant',
    variationName: 'Variant Name',
    add: 'ADD',
    edit: 'Edit',
    remove: 'Remove',
    addAnotherSize: 'ADD VARIANT ',
    imageValidationSize: 'Sorry, the uploaded image must be less than 10 mb',
    maximumVariantLimitReached: 'Maximum variant limit reached.',
    currencyName: 'GBP',

    //CONSUMER
    dontHaveAccount: "Don’t have an account?",
    signUp: "Sign up",
    forgotPassword: "Forgot Password?",
    email: "Email",
    password: "Password",
    signIn: "SIGN IN",
    next: "NEXT",
    personalDetails: "Personal details",
    tellUsWhoYouAre: "Tell us who you are",
    pleaseTellUsAboutYourself: "Please tell us a bit about yourself",
    shippingDetails: "Shipping details",
    addShippingDetailsForWhenYouPurchase: "Add shipping details for when you purchase",
    artistMerchandise: "Artist merchandise",
    neverMissAnArtist: "Never miss an Artist",
    weWillKeepYouUpToDate: "We’ll Keep you up to date with artists.",
    youCanCustomizeYourAlerts: "You can customize your alerts inside menu settings.",
    newArtistAdded: "New Artists Added",
    newContentAdded: "New Content Added",
    notificationPreviewWillBeShownWhether: "Notifications previews will be shown whether the phone is locked or unlocked. Show alerts on the lock screen, and in Notification Center.",
    allowNotifications: "ALLOW NOTIFICATIONS",
    maybeLater: "MAYBE LATER",
    thankYou: "Thank You!",
    yourAccountCreatedSuccessfully: "Your account was created successfully",
    done: "DONE",
    addYourPassword: "Add your email and Password",
    select3OrMoreIntrestedMusic: "Select 3 or more interested music genres",
    weWillBuildYourProfile: "We will build your profile based on your style",
    welcomeToBando: "Welcome to Bando, sign up to start",
    trueArtist: "exploring the artists",
    signUpAndSignin: 'Sign up/Sign in',
    subscribeToUnblockAllFeatures: 'Subscribe to Unblock all features',
    Merch: 'Merch',
    edit_profile: 'Edit Profile',
    edit_shipping_address: 'Edit Shipping Address',
    edit_interests: 'Edit Interests',

    buyNow: 'Buy Now',
    save: 'SAVE',
    paymentSuccess: 'Your payment was made successfully',
    select_at_least_3_genres_youre_interested_in_so: "Select at least 3 genres you’re interested in, so we can ensure the content on the app suits you well.",
    // we_can_ensure_the_content_on_the_app: "we can ensure the content on the app suits you well.",
    payment_Settings: "Payment Settings",
    viewAndManageYourSubscriptionsViewYourPurchases: "View and manage your subscriptions, view your purchases and manage the card details associated with your account.",
    Subscribe: 'Subscribe',
    artistContent: 'All artist content',
    noRestriction: 'with no restrictions',
    withoutLimit: 'All artists audio and videos without limits.',
    talkArtist: 'Talk with your favorite artists.',
    buyArtist: 'Buy your favorite artist merchandising.',
    profilePhoto: "photo",
    welcomeMessage: 'Welcome to Bando!',
    settingModalData1: 'Sorry!',
    settingModalData2: 'Having issues with an order? Get in contact with the artist using the chat functionality and they should be able to help.',
    settingModalData3: `If they're not able to help,you can reach out to Bando at support@bando-app.com and we'll help you with your dispute.`,
    chat: 'Chat',
    sorry: 'Sorry!',
    artistSorryMessageChat: `We're sorry,but you're not currently`,
    artistSorryMessageChat2: 'able to message this Artist.',
    artistSubcribeMessageChat: 'You need to be subcribed to this artist',
    artistSubcribeMessageChat2: 'to unlock this feature',
    deleteAccountSorry: 'Sorry, this Artist no longer has a',
    deleteAccountSorry1: 'Bando account',
    soldOut: 'Sold Out',
    sorryYouCantSubscribe: "Sorry, you can’t subscribe to an artist in the app. We know it’s a hassle, but we want to ensure that our artists are paid correctly. After you become a subscriber you can start listening within the app.",
    free: 'Access to exclusive Bando content',
    premium: `Access to Artist's Bando Pages with their music and videos`,
    cannotUpgradeToPremium: `You can't upgrade to premium in the app. We know its not ideal..`,
    bandoPremium: `Access to Bando pages of Artist's on Bando. View all their videos and music. Purchase their latest merch. Listen on- demand. Cancel anytime.`,
    bandoFreeAndPremium: "Bando Free and",
}
export default ConstStrings;