const AppConstant = {
    FIRST_NAME_REGX: /^([a-zA-z\s]{2,30})$/,
    PHONE_NUMBER_REGX: /^[0-9]{7}|[0-9]{13}$/,
    EMAIL_REGX: /^[^<>()[\]\\,;:\%#^\s@\"$&!@]+@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z0-9]+\.)+[a-zA-Z]{2,}))$/,
    FULL_NAME_REGEX: /^[a-zA-Z][a-zA-Z\s]*$/,
    NUMBER_REGEX: /^[0-9]+$/,
    ALPHANUMERIC_REGEX: /^[ a-zA-Z0-9]{7,16}$/,
    POSTAL_CODE_REGEX: /^[a-zA-Z0-9 ]{3,10}$/,
    ///^[a-zA-Z0-9]{3,10}$/,
    // PASSWORD_REGEX: /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,16}$/,
    PASSWORD_REGEX: /^(?=.{8,})(?=.*[A-Z])(?=.*\d).*$/,
    FLOAT_REGEX: /^(\d)+(\.\d+)?$/,
    ///^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,}$/,
    ZIP_CODE_REGX: /^[0-9\b]+$/,
    URL_REGEX: /(((www\.))[^\s]+)/g,
    URL_SOCIAL: /[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/,
    ANDROID: 'android',
    IOS: 'ios',
    localeEn: 'en',
    localeAr: 'ar',
    enter_phone_number: "Please enter valid phone number.",
    enter_email: "Please enter valid email",
    enter_password: "Please enter valid password",
    network_error_message: "Network Connection not established",
    network_error: "Network Error",
    something_went_wrong_message: "something went wrong",
    retry: "Retry",
    close: "Close",
    ok: "OK",
    ERROR: `Error!`,
    Bando: 'Bando',
    Please_enter_description: `Description field cannot be empty.`,
    oneCapitalRegex: /(?=.*[A-Z])/,
    oneNumberRegex: /(?=.*\d)/,
    aplphaNumeric: /^[a-zA-Z0-9]+$/i,
    bandoLogo: "https://bandoapp.s3.eu-west-2.amazonaws.com/storage/undefined/1630413070781_Banner%20Image.png",
    consumerArtistDetailUrl: 'https://api.bando-app.com/v1/artist/details',
    bandoBlockChatlogo: "https://bandoapp.s3.eu-west-2.amazonaws.com/storage/undefined/1628056800852_CardBackLogo%402x.png",
    bandoServer: `https://bando-app.com/v1/`, //production
    bandoStagingServer: `https://stagapi.bando-app.com/v1/`, //staging
    bandoTnCbaseUrl: `https://www.bando-app.com/`,
    stripePro: "pk_live_51IVixiB9n7a9AB4YSTg1SmPqHBfgHKbd6wGrOsgaKso60XKyq8rDnfQdsAYdRGDurxGqD2qnPHcPsdX7ewIWQAfy00UJ49e1EV",
    stripeDev: "pk_test_51IVixiB9n7a9AB4YoLc6tnqTdqVDSI5huNo7mtYfuLZeBRbfPibDyHAV2tugRaO831jrOgcuRHADn5bHhHL061fZ00rRuJfy4a",
    firebaseApple: "1rZukEbHs3Ql",
    iOSAppURL: "https://apps.apple.com/us/app/bando-fans/id1574520932",
    androidAppURL: "https://play.google.com/store/apps/details?id=com.bando_consumer",
    noRecordingAllowediOS: "As per the Bando's security policy recording a content is not allowed.",
    noScreenshotAllowediOS: "As per the Bando's security policy capturing a content is not allowed."
}

export default AppConstant;