export default {
    SET_FORGET_PASSWORD_RESET_TOKEN: 'SET_FORGET_PASSWORD_RESET_TOKEN',
    AUTH_SWITCH_ROUTE: "AUTH_SWITCH_ROUTE",

    SET_HOME_TAB: "SET_HOME_TAB",

    REGISTER_LOADING: "REGISTER_LOADING",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    IS_ARTIST_VERIFIED: "IS_ARTIST_VERIFIED",

    INTIAL_LOGIN_LOADING: "INTIAL_LOGIN_LOADING",
    INTIAL_LOGIN_SUCCESS: "INTIAL_LOGIN_SUCCESS",
    INTIAL_LOGIN_FAIL: "INTIAL_LOGIN_FAIL",

    SEND_OTP_LOADING: "SEND_OTP_LOADING",
    SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
    SEND_OTP_FAIL: "SEND_OTP_FAIL",

    VERIFY_OTP_LOADING: "VERIFY_OTP_LOADING",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAIL: "VERIFY_OTP_FAIL",

    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT_LOADING: 'LOGOUT_LOADING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',

    UPLOAD_FILE_LOADING: "UPLOAD_FILE_LOADING",
    UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
    UPLOAD_FILE_FAIL: "UPLOAD_FILE_FAIL",

    VERIFY_EMAIL_LOADING: "VERIFY_EMAIL_LOADING",
    VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
    VERIFY_EMAIL_FAIL: "VERIFY_EMAIL_FAIL",

    GET_POST_LIST_LOADING: "GET_POST_LIST_LOADING",
    GET_POST_LIST_SUCCESS: "GET_POST_LIST_SUCCESS",
    GET_POST_LIST_FAIL: "GET_POST_LIST_FAIL",

    DELETE_POST_LOADING: "DELETE_POST_LOADING",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    DELETE_POST_FAIL: "DELETE_POST_FAIL",

    DELETE_COMMENT_LOADING: "DELETE_COMMENT_LOADING",
    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL",

    GET_COMMENT_LIST_LOADING: "GET_COMMENT_LIST_LOADING",
    GET_COMMENT_LIST_SUCCESS: "GET_COMMENT_LIST_SUCCESS",
    GET_COMMENT_LIST_FAIL: "GET_COMMENT_LIST_FAIL",

    GET_REPLY_LIST_LOADING: "GET_REPLY_LIST_LOADING",
    GET_REPLY_LIST_SUCCESS: "GET_REPLY_LIST_SUCCESS",
    GET_REPLY_LIST_FAIL: "GET_REPLY_LIST_FAIL",

    REPLY_LOADING: "REPLY_LOADING",
    REPLY_SUCCESS: "REPLY_SUCCESS",
    REPLY_FAIL: "REPLY_FAIL",

    GET_MERCHLIST_LOADING: "GET_MERCHLIST_LOADING",
    GET_MERCHLIST_SUCCESS: "GET_MERCHLIST_SUCCESS",
    GET_MERCHLIST_FAIL: "GET_MERCHLIST_FAIL",

    CHANGE_MERCH_STATUS_LOADING: "CHANGE_MERCH_STATUS_LOADING",
    CHANGE_MERCH_STATUS_SUCCESS: "CHANGE_MERCH_STATUS_SUCCESS",
    CHANGE_MERCH_STATUS_FAIL: "CHANGE_MERCH_STATUS_FAIL",

    SET_REGISTRATION_DATA: "SET_REGISTRATION_DATA",
    SET_INITIAL_LOGIN_DATA: "SET_INITIAL_LOGIN_DATA",
    SET_NEW_POST_DATA: "SET_NEW_POST_DATA",
    GET_DATA_FROM_LOCAL: "GET_DATA_FROM_LOCAL",

    SET_LOCAL_DATA_POST: "SET_LOCAL_DATA_POST",

    GET_GENRE_SUCCESS: 'GET_GENRE_SUCCESS',
    GET_GENRE_FAIL: 'GET_GENRE_FAIL',

    NEW_POST_SUCCESS: 'NEW_POST_SUCCESS',
    NEW_POST_FAIL: 'NEW_POST_FAIL',

    FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",
    FORGET_PASSWORD_FAIL: 'FORGET_PASSWORD_FAIL',

    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
    EMAIL_NULL: 'EMAIL_NULL',
    SET_EMAIL: 'SET_EMAIL',
    SET_IMAGE_AUDIO: 'SET_IMAGE_AUDIO',
    CHANGE_VIDEO_NEW_POST_HANDLE_TOGGLE: 'CHANGE_VIDEO_NEW_POST_HANDLE_TOGGLE',

    CLEAR_NEW_POST_DATA: "CLEAR_NEW_POST_DATA",
    CLEAR_NEW_POST_COVER_IMAGE: 'CLEAR_NEW_POST_COVER_IMAGE',

    //New Merch
    SET_NEW_MERCH_DATA: 'SET_NEW_MERCH_DATA',
    CLEAR_NEW_MERCH_DATA: 'CLEAR_NEW_MERCH_DATA',
    CHANGE_PHOTO_OF_VISIBLE_INDEX: 'CHANGE_PHOTO_OF_VISIBLE_INDEX',
    SET_NEW_MERCH_IMAGE: `SET_NEW_MERCH_IMAGE`,

    POST_NEW_MERCH_SUCCESS: 'POST_NEW_MERCH_SUCCESS',
    POST_NEW_MERCH_FAIL: 'POST_NEW_MERCH_FAIL',
    POST_NEW_MERCH_LOADING: 'POST_NEW_MERCH_LOADING',

    //EDIT MERCH
    MERCH_TO_BE_EDIT: "MERCH_TO_BE_EDIT",
    SET_EDIT_MERCH_DATA: "SET_EDIT_MERCH_DATA",
    SET_EDIT_MERCH_STATUS: "SET_EDIT_MERCH_STATUS",

    EDIT_MERCH_LOADING: "EDIT_MERCH_LOADING",
    EDIT_MERCH_SUCCESS: "EDIT_MERCH_SUCCESS",
    EDIT_MERCH_FAIL: "EDIT_MERCH_FAIL",

    //artist detail
    GET_ARTIST_DETAILS_LOADING: "GET_ARTIST_DETAILS_LOADING",
    GET_ARTIST_DETATILS_SUCCESS: 'GET_ARTIST_DETATILS_SUCCESS',
    GET_ARTIST_DETATILS_FAIL: 'GET_ARTIST_DETATILS_FAIL',

    //Profile Detail Home data
    GET_PROFILE_DATA_INTO_HOMESCREEN: "GET_PROFILE_DATA_INTO_HOMESCREEN",


    //Edit Artisti Detail
    EDIT_ARTIST_DETAIL_LOADING: 'EDIT_ARTIST_DETAIL_LOADING',
    EDIT_ARTIST_DETAIL_SUCCESS: 'EDIT_ARTIST_DETAIL_SUCCESS',
    EDIT_ARTIST_DETAIL_FAIL: 'EDIT_ARTIST_DETAIL_FAIL',

    SAVE__LOCAL_DATA: 'SAVE_EDIT_PROFILE_LOCAL_DATA',


    //View all media
    VIEW_ALL_MEDIA_LOADING: 'VIEW_ALL_MEDIA_LOADING',
    VIEW_ALL_MEDIA_SUCCESS: 'VIEW_ALL_MEDIA_SUCCESS',
    VIEW_ALL_MEDIA_FAIL: 'VIEW_ALL_MEDIA_FAIL',


    //new type of consumer 
    SELECT_USER_GENRE: 'SELECT_USER_GENRE',

    GET_RECOMMENDED_FEED_LOADING: "GET_RECOMMENDED_FEED_LOADING",
    GET_RECOMMENDED_FEED_SUCCESS: "GET_RECOMMENDED_FEED_SUCCESS",
    GET_RECOMMENDED_FEED_FAIL: "GET_RECOMMENDED_FEED_FAIL",

    GET_TRENDING_LOADING: "GET_TRENDING_LOADING",
    GET_TRENDING_SUCCESS: "GET_TRENDING_SUCCESS",
    GET_TRENDING_FAIL: "GET_TRENDING_FAIL",

    GET_MYFEED_LOADING: "GET_MYFEED_LOADING",
    GET_MYFEED_SUCCESS: "GET_MYFEED_SUCCESS",
    GET_MYFEED_FAIL: "GET_MYFEED_FAIL",
    CLEAR_MY_FEED: "CLEAR_MY_FEED:",
    //search artist
    GET_SEARCH_ARTIST_LOADING: "GET_SEARCH_ARTIST_LOADING",
    GET_SEARCH_ARTIST_SUCCESS: "GET_SEARCH_ARTIST_SUCCESS",
    GET_SEARCH_ARTIST_FAIL: "GET_SEARCH_ARTIST_FAIL",
    GET_SEARCH_ARTIST_BY_NAME_LOADING: "GET_SEARCH_ARTIST_BY_NAME_LOADING",

    //get artist images
    GET_ARTIST_IMAGES_LOADING: "GET_ARTIST_IMAGES_LOADING",
    GET_ARTIST_IMAGES_SUCCESS: "GET_ARTIST_IMAGES_SUCCESS",
    GET_ARTIST_IMAGES_FAIL: "GET_ARTIST_IMAGES_FAIL",

    //get artist audio 
    GET_ARTIST_AUDIO_LOADING: 'GET_ARTIST_AUDIO_LOADING',
    GET_ARTIST_AUDIO_SUCCESS: "GET_ARTIST_AUDIO_SUCCESS",
    GET_ARTIST_AUDIO_FAIL: "GET_ARTIST_AUDIO_FAIL",


    //get artist video
    GET_ARTIST_VIDEO_LOADING: 'GET_ARTIST_VIDEO_LOADING',
    GET_ARTIST_VIDEO_SUCCESS: "GET_ARTIST_VIDEO_SUCCESS",
    GET_ARTIST_VIDEO_FAIL: "GET_ARTIST_VIDEO_FAIL",

    // set Artist Id 
    SET_ARTIST_ID: 'SET_ARTIST_ID',

    //Edit Artisti Detail
    EDIT_CONSUMER_PROFILE_DETAIL_LOADING: 'EDIT_CONSUMER_PROFILE_DETAIL_LOADING',
    EDIT_CONSUMER_PROFILE_DETAIL_SUCCESS: 'EDIT_CONSUMER_PROFILE_DETAIL_SUCCESS',
    EDIT_CONSUMER_PROFILE_DETAIL_FAIL: 'EDIT_CONSUMER_PROFILE_DETAIL_FAIL',

    UPDATING_SHIPPING_ADDRESS_SUCCESS: 'UPDATING_SHIPPING_ADDRESS_SUCCESS',
    UPDATING_SHIPPING_ADDRESS: 'UPDATING_SHIPPING_ADDRESS',

    //subcribe
    SUBSCRIBE_LOADING: 'SUBSCRIBE_LOADING',
    SUBSCRIBE_SUCCESS: 'SUBSCRIBE_SUCCESS',
    SUBCRIBE_FAIL: 'SUBCRIBE_FAIL',

    //buy merch
    BUY_MERCH_LOADING: 'BUY_MERCH_LOADING',
    BUY_MERCH_SUCCESS: 'BUY_MERCH_SUCCESS',
    BUY_MERCH_FAIL: 'BUY_MERCH_FAIL',

    //handle payment success modal
    IS_PAYMENT_SUCCESS: 'IS_PAYMENT_SUCCESS',

    //social login
    SET_SOCIAL_LOGIN_REGISTRATION_DATA: 'SET_SOCIAL_LOGIN_REGISTRATION_DATA',
    //POST COMMENT
    POST_COMMENT_LOADING: "POST_COMMENT_LOADING",
    POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
    POST_COMMENT_FAIL: "POST_COMMENT_FAIL",

    //PURCHASES LIST
    PURCHASES_LIST_LOADING: "PURCHASES_LIST_LOADING",
    PURCHASES_LIST_SUCCESS: "PURCHASES_LIST_SUCCESS",
    PURCHASES_LIST_FAIL: "PURCHASES_LIST_FAIL",

    //SUBSCRIPTION LIST
    SUBSCRIPTION_LIST_LOADING: "SUBSCRIPTION_LIST_LOADING",
    SUBSCRIPTION_LIST_SUCCESS: "SUBSCRIPTION_LIST_SUCCESS",
    SUBSCRIPTION_LIST_FAIL: "SUBSCRIPTION_LIST_FAIL",

    //UNSUBSCRIBE ARTIST
    UNSUBSCRIBE_ARTIST_LOADING: "UNSUBSCRIBE_ARTIST_LOADING",
    UNSUBSCRIBE_ARTIST_SUCCESS: "UNSUBSCRIBE_ARTIST_SUCCESS",
    UNSUBSCRIBE_ARTIST_FAIL: "SUBSCRIPTION_LIST_FAIL",
    //Notifciation data
    HANDLE_NOTIFICATION_DATA: "HANDLE_NOTIFICATION_DATA",

    // get Notification
    GET_NOTIFICATION_DATA_LOADING: 'GET_NOTIFICATION_DATA_LOADING',
    GET_NOTIFICATION_DATA_SUCCESS: 'GET_NOTIFICATION_DATA_SUCCESS',
    GET_NOTIFICATION_DATA_FAIL: 'GET_NOTIFICATION_DATA_FAIL',

    //clear Notification data
    CLEAR_NOTIFICATION_DATA_WHEN_TOGGLE: 'CLEAR_NOTIFICATION_DATA_WHEN_TOGGLE',

    //update Notification
    VIEW_NOTIFICATION_LOADING: 'VIEW_NOTIFICATION_LOADING',
    VIEW_NOTIFICATION_SUCCESS: 'VIEW_NOTIFICATION_SUCCESS',
    VIEW_NOTIFICATION_FAIL: 'VIEW_NOTIFICATION_FAIL',

    //GET CARDS LIST
    GET_CARDS_LIST_LOADING: "GET_CARDS_LIST_LOADING",
    GET_CARDS_LIST_SUCCESS: "GET_CARDS_LIST_SUCCESS",
    GET_CARDS_LIST_FAIL: "GET_CARDS_LIST_FAIL",

    //DELETE_PAYMENT_CARD
    DELETE_PAYMENT_CARD_LOADING: "DELETE_PAYMENT_CARD_LOADING",
    DELETE_PAYMENT_CARD_SUCCESS: "DELETE_PAYMENT_CARD_SUCCESS",
    DELETE_PAYMENT_CARD_FAIL: "DELETE_PAYMENT_CARD_FAIL",

    //UNSUBSCRIBE ARTIST
    UNSUBSCRIBE_ARTIST_LOADING: "UNSUBSCRIBE_ARTIST_LOADING",
    UNSUBSCRIBE_ARTIST_SUCCESS: "UNSUBSCRIBE_ARTIST_SUCCESS",
    UNSUBSCRIBE_ARTIST_FAIL: "SUBSCRIPTION_LIST_FAIL",

    //IS AUDIO PLAYING IN MINIMIZED
    AUDIO_PLAYING_MINIMIZED: "AUDIO_PLAYING_MINIMIZED",

    //POST LIKE UNLIKE
    POST_LIKE_LOADING: "POST_LIKE_LOADING",
    POST_LIKE_SUCCESS: "POST_LIKE_SUCCESS",
    POST_LIKE_FAIL: "POST_LIKE_FAIL",

    //POST UNLIKE UNLIKE
    POST_UNLIKE_LOADING: "POST_LIKE_LOADING",
    POST_UNLIKE_SUCCESS: "POST_LIKE_SUCCESS",
    POST_UNLIKE_FAIL: "POST_LIKE_FAIL",

    //SET SELECTED POST
    SET_SELECTED_POST: "SET_SELECTED_POST",
    //SUBSCRIBED ARTIST LIST
    SUBSCRIBE_ARTIST_LIST_LOADING: 'SUBSCRIBE_ARTIST_LIST_LOADING',
    SUBSCRIBE_ARTIST_LIST_SUCCESS: 'SUBSCRIBE_ARTIST_LIST_SUCCESS',
    SUBSCRIBE_ARTIST_LIST_FAIL: 'SUBSCRIBE_ARTIST_LIST_FAIL',

    //SUBSCRIBED ARTIST CHAT LIST
    SUBCRIBED_ARTIST_CHAT_LIST_LOADING: 'SUBCRIBED_ARTIST_CHAT_LIST_LOADING',
    SUBCRIBED_ARTIST_CHAT_LIST_SUCCESS: 'SUBCRIBED_ARTIST_CHAT_LIST_SUCCESS',
    SUBCRIBED_ARTIST_CHAT_LIST_FAIL: 'SUBCRIBED_ARTIST_CHAT_LIST_FAIL',

    //SEARCH ARTIST FOR CHAT
    SEARCH_ARTIST_FOR_CHAT_LOADING: 'SEARCH_ARTIST_FOR_CHAT_LOADING',
    SEARCH_ARTIST_FOR_CHAT_SUCCESS: 'SEARCH_ARTIST_FOR_CHAT_SUCCESS',
    SEARCH_ARTIST_FOR_CHAT_FAIL: 'SEARCH_ARTIST_FOR_CHAT_FAIL',

    //POST LAST CHAT MESSAGE
    POST_LAST_CHAT_MESSAGE_LOADING: 'POST_LAST_CHAT_MESSAGE_LOADING',
    POST_LAST_CHAT_MESSAGE_SUCCESS: 'POST_LAST_CHAT_MESSAGE_SUCCESS',
    POST_LAST_CHAT_MESSAGE_FAIL: 'POST_LAST_CHAT_MESSAGE_FAIL',

    //CLEAR SEARCH ARTIST FOR CHAT
    CLEAR_SEARCH_ARTIST_FOR_CHAT: 'CLEAR_SEARCH_ARTIST_FOR_CHAT',

    //SET FIREBASE MESSAGE
    SET_FIREBASE_MESSAGE: 'SET_FIREBASE_MESSAGE',
    //CLEAR FIREBASE MESSAGE
    CLEAR_FIREBASE_MESSAGE: 'CLEAR_FIREBASE_MESSAGE',

    //SET NAVIGATION OF SUBCRIBED FROM CHAT TO HOME
    SET_NAVIGATION_FOR_SUBCRIBED_CHAT: 'SET_NAVIGATION_FOR_SUBCRIBED_CHAT',

    //CLEAN NAVIGATION OF SUBCRIBED FROM CHAT TO HOME
    CLEAN_NAVIGATION_FOR_SUBCRIBED_CHAT: 'CLEAN_NAVIGATION_FOR_SUBCRIBED_CHAT',


    //SET DATA FOR RECENT CHAT
    SET_DATA_FOR_RECENT_CHAT: 'SET_DATA_FOR_RECENT_CHAT',

    //REPORT POST
    REPORT_POST_LOADING: 'REPORT_POST_LOADING',
    REPORT_POST_SUCCESS: 'REPORT_POST_SUCCESS',
    REPORT_POST_FAIL: 'REPORT_POST_FAIL',


    //SHARE POST    
    SHARE_POST_LOADING: "SHARE_POST_LOADING",
    SHARE_POST_SUCCESS: "SHARE_POST_SUCCESS",
    SHARE_POST_FAIL: "SHARE_POST_FAIL",

    //TRACK POST
    TRACK_POST_LOADING: 'TRACK_POST_LOADING',
    TRACK_POST_SUCCESS: "TRACK_POST_SUCCESS",
    TRACK_POST_FAIL: "TRACK_POST_FAIL",

    //GET POST DETAILS
    GET_POST_DETAILS_LOADING: 'GET_POST_DETAILS_LOADING',
    GET_POST_DETAILS_SUCCESS: 'GET_POST_DETAILS_SUCCESS',
    GET_POST_DETAILS_FAIL: 'GET_POST_DETAILS_FAIL',
    //SEND FCM TOKEN
    SEND_FCM_TOKEN_LOADING: 'SEND_FCM_TOKEN_LOADING',
    SEND_FCM_TOKEN_SUCCESS: 'SEND_FCM_TOKEN_SUCCESS',
    SEND_FCM_TOKEN_FAIL: 'SEND_FCM_TOKEN_FAIL',

    BUY_MERCH_FINAL_LOADING: "BUY_MERCH_FINAL_LOADING",
    BUY_MERCH_FINAL_SUCCESS: "BUY_MERCH_FINAL_SUCCESS",
    BUY_MERCH_FINAL_FAIL: "BUY_MERCH_FINAL_FAIL",
    CLEAR_FORGET_PASSWORD: 'CLEAR_FORGET_PASSWORD',

    SET_FIREBASE_UID_LOADING: "SET_FIREBASE_UID_LOADING",
    SET_FIREBASE_UID_SUCCESS: "SET_FIREBASE_UID_SUCCESS",
    SET_FIREBASE_UID_FAIL: 'SET_FIREBASE_UID_FAIL',

    // NEW ARTIST NOTIFICATION

    SET_NEW_ARTIST_NOTIFICATION_LOADING: 'SET_NEW_ARTIST_NOTIFICATION_LOADING',
    SET_NEW_ARTIST_NOTIFICATION_SUCCESS: 'SET_NEW_ARTIST_NOTIFICATION_SUCCESS',
    SET_NEW_ARTIST_NOTIFICATION_FAIL: 'SET_NEW_ARTIST_NOTIFICATION_FAIL',

    //NEW CONTENT NOTIFICATION

    SET_NEW_CONTENT_NOTIFICATION_LOADING: 'SET_NEW_CONTENT_NOTIFICATION_LOADING',
    SET_NEW_CONTENT_NOTIFICATION_SUCCESS: 'SET_NEW_CONTENT_NOTIFICATION_SUCCESS',
    SET_NEW_CONTENT_NOTIFICATION_FAIL: 'SET_NEW_CONTENT_NOTIFICATION_FAIL',

    //HANDLE PAYMENT LOADER
    HANDLE_PAYMENT_LOADER: 'HANDLE_PAYMENT_LOADER',

    //SET SEARCH PARAMS OF FIREBASE

    SET_SEARCH_PARAMS_OF_FIREBASE: 'SET_SEARCH_PARAMS_OF_FIREBASE',

    // IS APPLE LOGIN

    IS_APPLE_LOGIN: 'IS_APPLE_LOGIN',

    CLEAR_COMMENT_LIST: "CLEAR_COMMENT_LIST",
    CLEAR_REPLY_LIST: "CLEAR_REPLY_LIST",
    CLEAR_HOME_DATA: "CLEAR_HOME_DATA",
    CLEAR_ARTIST_DETAIL: "CLEAR_ARTIST_DETAIL",
    CLEAR_ALL_DATA: "CLEAR_ALL_DATA",

    REFRESH_TOKEN_LOADING: "REFRESH_TOKEN_LOADING",
    REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
    REFRESH_TOKEN_FAIL: "REFRESH_TOKEN_FAIL",

    GET_COLLECTION_LIST_LOADING: "GET_COLLECTION_LIST_LOADING",
    GET_COLLECTION_LIST_SUCCESS: "GET_COLLECTION_LIST_SUCCESS",
    GET_COLLECTION_LIST_FAIL: "GET_COLLECTION_LIST_FAIL",

    ADD_COLLECTION_LOADING: "ADD_COLLECTION_LOADING",
    ADD_COLLECTION_SUCCESS: "ADD_COLLECTION_SUCCESS",
    ADD_COLLECTION_FAIL: "ADD_COLLECTION_FAIL",

    UPDATE_COLLECTION_LOADING: "UPDATE_COLLECTION_LOADING",
    UPDATE_COLLECTION_SUCCESS: "UPDATE_COLLECTION_SUCCESS",
    UPDATE_COLLECTION_FAIL: "UPDATE_COLLECTION_FAIL",

    DELETE_COLLECTION_LOADING: "DELETE_COLLECTION_LOADING",
    DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
    DELETE_COLLECTION_FAIL: "DELETE_COLLECTION_FAIL",

    GET_COLLECTION_DETAILS_LOADING: "GET_COLLECTION_DETAILS_LOADING",
    GET_COLLECTION_DETAILS_SUCCESS: "GET_COLLECTION_DETAILS_SUCCESS",
    GET_COLLECTION_DETAILS_FAIL: "GET_COLLECTION_DETAILS_FAIL",

    GET_MERCH_DETAIL_LOADING: "GET_MERCH_DETAIL_LOADING",
    GET_MERCH_DETAIL_SUCCESS: "GET_MERCH_DETAIL_SUCCESS",
    GET_MERCH_DETAIL_FAIL: "GET_MERCH_DETAIL_FAIL",

    REQUEST_DELETE_MY_ACCOUNT_LOADING: "REQUEST_DELETE_MY_ACCOUNT_LOADING",
    REQUEST_DELETE_MY_ACCOUNT_SUCCESS: "REQUEST_DELETE_MY_ACCOUNT_SUCCESS",
    REQUEST_DELETE_MY_ACCOUNT_FAIL: "REQUEST_DELETE_MY_ACCOUNT_FAIL",

    REQUEST_CHANGE_CREDENTIAL_LOADING: "REQUEST_CHANGE_CREDENTIAL_LOADING",
    REQUEST_CHANGE_CREDENTIAL_SUCCESS: "REQUEST_CHANGE_CREDENTIAL_SUCCESS",
    REQUEST_CHANGE_CREDENTIAL_FAIL: "REQUEST_CHANGE_CREDENTIAL_FAIL",

    SCREENSHOT_TAKEN: "SCREENSHOT_TAKEN",
}